version: "3"
services:
  django:
    build: .
    container_name: django
    command:
      - bash
      - -c
      - |
        python manage.py runserver
    networks:
      - elastic
    ports:
      - 8000:8000
    volumes:
      - ${PWD}:/home/django
    expose:
      - 8000
    restart: always

